# Generated by Django 5.1.6 on 2025-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
